name: Cadernetadofiado
description: ProvaFlutter.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_slidable: ^1.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  build_runner: ^2.1.11
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/image/logo.jpg
